# fly.toml app configuration file generated for dam-fastapi on 2025-04-30T20:40:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dam-fastapi'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
